// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var ListLabels = require("bs-platform/lib/js/listLabels.js");

var pageTitle = Css.style(/* :: */[
      Css.fontSize(Css.em(1.2)),
      /* :: */[
        Css.marginBottom(Css.em(0.5)),
        /* [] */0
      ]
    ]);

function combineClasses(classes) {
  return ListLabels.fold_left((function (r, elem) {
                return r + (" " + elem);
              }), "", classes);
}

exports.pageTitle = pageTitle;
exports.combineClasses = combineClasses;
/* pageTitle Not a pure module */
