// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Nav$Whatever = require("./Nav.bs.js");
var Utils$Whatever = require("../Utils.bs.js");

Css.$$global("body, html", /* :: */[
      Css.padding(Css.px(0)),
      /* :: */[
        Css.margin(Css.px(0)),
        /* :: */[
          Css.fontFamily(Utils$Whatever.defaultFont),
          /* :: */[
            Css.fontSize(Css.px(16)),
            /* [] */0
          ]
        ]
      ]
    ]);

var homeContainer = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.alignItems(Css.center),
          /* :: */[
            Css.justifyContent(Css.center),
            /* :: */[
              Css.height(Css.vh(100.0)),
              /* :: */[
                Css.fontSize(Css.rem(1.5)),
                /* :: */[
                  Css.backgroundColor(Css.hex("232529")),
                  /* :: */[
                    Css.color(Css.white),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var firstName = Css.style(/* :: */[
      Css.fontSize(Css.em(5.0)),
      /* :: */[
        Css.color(Css.white),
        /* :: */[
          Css.marginBottom(Css.em(0.1)),
          /* :: */[
            Css.textAlign(/* left */-944764921),
            /* [] */0
          ]
        ]
      ]
    ]);

var lastName = Css.style(/* :: */[
      Css.fontSize(Css.em(1.0)),
      /* :: */[
        Css.textAlign(/* left */-944764921),
        /* [] */0
      ]
    ]);

var bio = Css.style(/* :: */[
      Css.fontSize(Css.em(0.8)),
      /* :: */[
        Css.margin(Css.em(0.2)),
        /* [] */0
      ]
    ]);

var Styles = /* module */[
  /* homeContainer */homeContainer,
  /* firstName */firstName,
  /* lastName */lastName,
  /* bio */bio
];

var component = ReasonReact.statelessComponent("Home");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: homeContainer
                }, ReasonReact.element(/* None */0, /* None */0, Nav$Whatever.make(/* array */[])), React.createElement("section", undefined, React.createElement("header", undefined, React.createElement("h1", {
                              className: firstName
                            }, Utils$Whatever.text("Akin")), React.createElement("h2", {
                              className: lastName
                            }, Utils$Whatever.text("Sowemimo"))), React.createElement("article", undefined, React.createElement("p", {
                              className: bio
                            }, Utils$Whatever.text("Software Developer,")), React.createElement("p", {
                              className: bio
                            }, Utils$Whatever.text("One time doctor,")), React.createElement("p", {
                              className: bio
                            }, Utils$Whatever.text("often times problem solver,")), React.createElement("p", {
                              className: bio
                            }, Utils$Whatever.text("occasionaly weeps with frustration")))));
    });
  return newrecord;
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/*  Not a pure module */
