// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$Whatever = require("../Utils.bs.js");

var navContainer = Css.style(/* :: */[
      Css.position(/* absolute */-1013592457),
      /* :: */[
        Css.height(Css.em(3.0)),
        /* :: */[
          Css.width(Css.vw(100.0)),
          /* :: */[
            Css.top(Css.px(0)),
            /* :: */[
              Css.fontSize(Css.rem(0.8)),
              /* :: */[
                Css.display(/* flex */-1010954439),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var links = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(/* row */5693978),
        /* :: */[
          Css.alignSelf(/* flexEnd */924268066),
          /* :: */[
            Css.width(Css.vw(40.0)),
            /* [] */0
          ]
        ]
      ]
    ]);

var listItem = Css.style(/* :: */[
      Css.flex(1),
      /* :: */[
        Css.fontSize(Css.em(1.2)),
        /* :: */[
          Css.hover(/* :: */[
                Css.textDecoration(/* underline */131142924),
                /* [] */0
              ]),
          /* :: */[
            Css.whiteSpace(/* nowrap */867913355),
            /* [] */0
          ]
        ]
      ]
    ]);

var Styles = /* module */[
  /* navContainer */navContainer,
  /* links */links,
  /* listItem */listItem
];

var component = ReasonReact.statelessComponent("NavigationBar");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("nav", {
                  className: navContainer
                }, React.createElement("ul", {
                      className: links
                    }, React.createElement("li", {
                          className: listItem
                        }, Utils$Whatever.text("Stuff I've done")), React.createElement("li", {
                          className: listItem
                        }, Utils$Whatever.text("More about me")), React.createElement("li", {
                          className: listItem
                        }, Utils$Whatever.text("Interests and Experience"))), React.createElement("div", undefined, React.createElement("i", {
                          className: "fas fa-camera-retro"
                        })));
    });
  return newrecord;
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/* navContainer Not a pure module */
