// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$Portfolio = require("../Utils.bs.js");

var component = ReasonReact.statelessComponent("Projects");

var projectContainer = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.justifyContent(Css.spaceAround),
          /* :: */[
            Css.alignItems(Css.center),
            /* :: */[
              Css.width(/* `percent */[
                    -119887163,
                    100
                  ]),
              /* :: */[
                Css.minHeight(/* `percent */[
                      -119887163,
                      100
                    ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var pageTitle = Css.style(/* :: */[
      Css.fontSize(Css.em(1.2)),
      /* :: */[
        Css.marginBottom(Css.em(0.5)),
        /* [] */0
      ]
    ]);

var Styles = /* module */[
  /* projectContainer */projectContainer,
  /* pageTitle */pageTitle
];

var card = Css.style(/* :: */[
      Css.width(/* `percent */[
            -119887163,
            50
          ]),
      /* :: */[
        Css.backgroundColor(Css.whitesmoke),
        /* :: */[
          Css.height(/* `percent */[
                -119887163,
                50
              ]),
          /* :: */[
            Css.borderRadius(Css.px(8)),
            /* :: */[
              Css.color(Css.black),
              /* :: */[
                Css.padding(Css.em(1)),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var component$1 = ReasonReact.statelessComponent("Card");

function make(title, children) {
  var newrecord = component$1.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("article", {
                  className: card
                }, React.createElement("h1", undefined, Utils$Portfolio.str(title)), children);
    });
  return newrecord;
}

var Card = /* module */[
  /* card */card,
  /* component */component$1,
  /* make */make
];

function make$1() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: projectContainer
                }, React.createElement("h1", {
                      className: pageTitle
                    }, Utils$Portfolio.str("Projects")), ReasonReact.element(/* None */0, /* None */0, make("Onivim", /* array */[Utils$Portfolio.str("A modal editor for the modern age")])));
    });
  return newrecord;
}

exports.component = component;
exports.Styles = Styles;
exports.Card = Card;
exports.make = make$1;
/* component Not a pure module */
