// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Transition");

function make(before, after, children) {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function (self) {
      setTimeout(Curry._1(self[/* reduce */1], (function () {
                  return /* Style */[after];
                })), 0);
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function (param) {
      return React.createElement("div", {
                  style: param[/* state */2]
                }, children);
    });
  newrecord[/* initialState */10] = (function () {
      return before;
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [action[0]]);
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
