// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var ListLabels = require("bs-platform/lib/js/listLabels.js");

var pageTitle = Css.style(/* :: */[
      Css.fontSize(Css.em(1.2)),
      /* :: */[
        Css.marginBottom(Css.em(0.5)),
        /* [] */0
      ]
    ]);

function flexCenter(columnStyle) {
  return /* :: */[
          Css.display(Css.flexBox),
          /* :: */[
            Css.alignItems(Css.center),
            /* :: */[
              Css.justifyContent(Css.center),
              /* :: */[
                Css.flexDirection(columnStyle !== 0 ? Css.column : Css.row),
                /* [] */0
              ]
            ]
          ]
        ];
}

function combineClasses(classes) {
  return ListLabels.fold_left((function (r, elem) {
                return r + (" " + elem);
              }), "", classes);
}

var theme = /* record */[/* background */Css.hex("232529")];

exports.pageTitle = pageTitle;
exports.flexCenter = flexCenter;
exports.combineClasses = combineClasses;
exports.theme = theme;
/* pageTitle Not a pure module */
