// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$Portfolio = require("./Utils.bs.js");
var CommonStyles$Portfolio = require("./CommonStyles.bs.js");

var hpo = require("./assets/hpo.png");

var onivim = require("./assets/oni-logo.png");

import("./css/projects.css");

var component = ReasonReact.statelessComponent("Projects");

var container = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.justifyContent(Css.spaceAround),
          /* :: */[
            Css.alignItems(Css.center),
            /* :: */[
              Css.width(/* `percent */[
                    -119887163,
                    100
                  ]),
              /* :: */[
                Css.overflow(Css.scroll),
                /* :: */[
                  Css.height(Css.auto),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var image = Css.style(/* :: */[
      Css.width(Css.em(10)),
      /* :: */[
        Css.height(Css.auto),
        /* :: */[
          Css.margin(Css.em(1)),
          /* [] */0
        ]
      ]
    ]);

var cards = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.row),
        /* :: */[
          Css.flexWrap(Css.wrap),
          /* :: */[
            Css.children(/* :: */[
                  Css.margin(Css.em(2)),
                  /* :: */[
                    Css.flexBasis(/* `percent */[
                          -119887163,
                          35
                        ]),
                    /* [] */0
                  ]
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var line = Css.style(/* :: */[
      Css.display(Css.block),
      /* [] */0
    ]);

var intro = Css.style(/* :: */[
      Css.fontStyle(Css.italic),
      /* :: */[
        Css.fontWeight(800),
        /* [] */0
      ]
    ]);

var title = Css.style(/* :: */[
      Css.height(Css.em(5)),
      /* :: */[
        Css.verticalAlign(Css.middle),
        /* :: */[
          Css.textAlign(Css.center),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[
  /* container */container,
  /* image */image,
  /* cards */cards,
  /* line */line,
  /* intro */intro,
  /* title */title
];

var card = Css.style(/* :: */[
      Css.flex(1),
      /* :: */[
        Css.height(Css.auto),
        /* :: */[
          Css.backgroundColor(Css.whitesmoke),
          /* :: */[
            Css.marginTop(Css.em(1)),
            /* :: */[
              Css.marginBottom(Css.em(1)),
              /* :: */[
                Css.borderRadius(Css.px(5)),
                /* :: */[
                  Css.color(Css.black),
                  /* :: */[
                    Css.fontSize(Css.rem(1.2)),
                    /* :: */[
                      Css.overflow(Css.hidden),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var content = Css.style(/* :: */[
      Css.margin(Css.zero),
      CommonStyles$Portfolio.flexCenter(/* true */1)
    ]);

var contentBody = Css.style(/* [] */0);

var details = Css.style(/* :: */[
      Css.lineHeight(1.5),
      /* :: */[
        Css.width(/* `percent */[
              -119887163,
              100
            ]),
        /* :: */[
          Css.padding(Css.em(1)),
          /* :: */[
            Css.boxSizing(Css.borderBox),
            /* [] */0
          ]
        ]
      ]
    ]);

var imageContainer = Css.style(/* :: */[
      Css.width(/* `percent */[
            -119887163,
            100
          ]),
      /* :: */[
        Css.backgroundColor(Css.hex("EFEFEF")),
        /* :: */[
          Css.minHeight(/* `percent */[
                -119887163,
                40
              ]),
          CommonStyles$Portfolio.flexCenter(/* true */1)
        ]
      ]
    ]);

var cardTitle = Css.style(/* :: */[
      Css.margin(Css.em(0.2)),
      /* [] */0
    ]);

var component$1 = ReasonReact.statelessComponent("Card");

function make(title, children) {
  var newrecord = component$1.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("article", {
                  className: card
                }, React.createElement("h1", {
                      className: cardTitle
                    }, Utils$Portfolio.str(title)), children);
    });
  return newrecord;
}

var Card = /* module */[
  /* card */card,
  /* content */content,
  /* contentBody */contentBody,
  /* details */details,
  /* imageContainer */imageContainer,
  /* cardTitle */cardTitle,
  /* component */component$1,
  /* make */make
];

function renderText(details) {
  return $$Array.mapi((function (index, line$1) {
                return React.createElement("span", {
                            key: String(index),
                            className: line
                          }, Utils$Portfolio.str(line$1));
              }), details);
}

var oniDetails = /* array */[
  "I collaborate on the Onivim project on github.",
  "Oni is an attempt to modernise modal editing using vim.",
  "Whilst taking inspiration from more modern editors like VSCode and Atom.",
  "As a collaborator I triage and respond to issues, contribute new functionality and fix bugs",
  "It uses React, Redux, RxJs, TypeScript, Electron"
];

var phenotypeDetails = /* array */[
  " The object of this project was to create a data visualization of a section of the\n  human phenotype ontology (HPO)",
  " The HPO is fancy term for the classification of human disease, aka the main classification\n    of lungs diseases would be pulmonary pathology and this would then have loads of subclasses\n  ",
  " This involved parsing an enormous OBO file (an obscure academic format for phenotypic data) into\n  json and then rendering this data with a data visualisation library\n    "
];

function make$1() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: container
                }, React.createElement("h1", {
                      className: CommonStyles$Portfolio.combineClasses(/* :: */[
                            CommonStyles$Portfolio.pageTitle,
                            /* :: */[
                              title,
                              /* [] */0
                            ]
                          ])
                    }, Utils$Portfolio.str("Projects")), React.createElement("section", {
                      className: cards
                    }, ReasonReact.element(/* None */0, /* None */0, make("Onivim", /* array */[React.createElement("div", {
                                    className: content
                                  }, React.createElement("div", {
                                        className: imageContainer
                                      }, React.createElement("img", {
                                            className: image,
                                            alt: "onivim logo",
                                            src: onivim
                                          })), React.createElement("div", {
                                        className: details
                                      }, React.createElement("p", {
                                            className: intro
                                          }, Utils$Portfolio.str("A Modal Editor for the Modern age")), React.createElement("p", {
                                            className: contentBody
                                          }, renderText(oniDetails))))])), ReasonReact.element(/* None */0, /* None */0, make("Human Phenotype Ontology", /* array */[React.createElement("div", {
                                    className: content
                                  }, React.createElement("div", {
                                        className: imageContainer
                                      }, React.createElement("img", {
                                            className: image,
                                            alt: "onivim logo",
                                            src: hpo
                                          })), React.createElement("div", {
                                        className: details
                                      }, React.createElement("p", {
                                            className: intro
                                          }, Utils$Portfolio.str("A data visualization of the human phenotype ontology")), React.createElement("p", {
                                            className: contentBody
                                          }, renderText(phenotypeDetails))))])), ReasonReact.element(/* None */0, /* None */0, make("Human Phenotype Ontology", /* array */[React.createElement("div", {
                                    className: content
                                  }, React.createElement("div", {
                                        className: imageContainer
                                      }, React.createElement("img", {
                                            className: image,
                                            alt: "onivim logo",
                                            src: hpo
                                          })), React.createElement("div", {
                                        className: details
                                      }, React.createElement("p", {
                                            className: intro
                                          }, Utils$Portfolio.str("A data visualization of the human phenotype ontology")), React.createElement("p", {
                                            className: contentBody
                                          }, renderText(phenotypeDetails))))]))));
    });
  return newrecord;
}

exports.hpo = hpo;
exports.onivim = onivim;
exports.component = component;
exports.Styles = Styles;
exports.Card = Card;
exports.renderText = renderText;
exports.oniDetails = oniDetails;
exports.phenotypeDetails = phenotypeDetails;
exports.make = make$1;
/* hpo Not a pure module */
