// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var prompt = "/Users/akin_sowemimo/root";

var about = /* array */[
  "I trained as a Medical Doctor at King's college london.",
  "Unfortunately after 8 years of studying, training, many an up and down\n      I realised that it wasn\'t for me and parted ways with that time of my life.\n        ",
  " As understandeably unusual a choice as it might seem I much preferred tinkering with computers\n      I\'d spent much of my youth messing around with hardware but it wasn\'t really till the fateful summer having just\n      decided to leave my job that I discovered github and the rest is history...\n      ",
  "Actually the rest is me meeting a bunch of other aspiring developers, our forming a group to teach each other\n      then my finding out about founders and coders in London"
];

function showPrompt() {
  return "/Users/akin_sowemimo/root:";
}

var filenames = /* array */["about.txt"];

var files = /* record */[/* about */about];

function cat(arg) {
  if (arg === "about.txt") {
    return /* ShellSuccess */Block.__(0, [about]);
  } else {
    return /* ShellFailure */Block.__(1, ["Sorry that file is invalid"]);
  }
}

function parseInput(input, arg) {
  switch (input) {
    case "cat" : 
        return cat(arg);
    case "ls" : 
        return /* ShellSuccess */Block.__(0, [filenames]);
    default:
      return /* ShellFailure */Block.__(1, ["Sorry that command is invalid"]);
  }
}

var errorsMessages = /* record */[
  /* invalid_dir */"Sorry the directory is invalid",
  /* invalid_cmd */"Sorry that command is invalid",
  /* invalid_file */"Sorry that file is invalid"
];

var commands = /* record */[
  /* ls */"ls",
  /* cat */"cat"
];

exports.errorsMessages = errorsMessages;
exports.commands = commands;
exports.prompt = prompt;
exports.about = about;
exports.showPrompt = showPrompt;
exports.filenames = filenames;
exports.files = files;
exports.cat = cat;
exports.parseInput = parseInput;
/* No side effect */
