// Generated by BUCKLESCRIPT VERSION 3.1.1, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$Portfolio = require("./Utils.bs.js");
var CommonStyles$Portfolio = require("./CommonStyles.bs.js");

var component = ReasonReact.statelessComponent("Titlebar");

var buttonContainer = Css.style(/* :: */[
      Css.left(Css.zero),
      /* :: */[
        Css.position(Css.absolute),
        /* [] */0
      ]
    ]);

var buttons = Css.style(/* :: */[
      Css.height(Css.em(1.5)),
      /* :: */[
        Css.width(Css.em(1.5)),
        /* :: */[
          Css.borderRadius(/* `percent */[
                -119887163,
                50
              ]),
          /* :: */[
            Css.border(Css.px(0), Css.solid, Css.hex("000")),
            /* :: */[
              Css.position(Css.relative),
              /* :: */[
                Css.top(Css.em(0.3)),
                /* :: */[
                  Css.left(Css.em(1)),
                  /* :: */[
                    Css.marginRight(Css.em(0.5)),
                    /* :: */[
                      Css.backgroundColor(Css.hex("ff3b47")),
                      /* :: */[
                        Css.borderColor(Css.hex("9d252b")),
                        /* :: */[
                          Css.display(Css.inlineBlock),
                          /* :: */[
                            Css.fontSize(Css.em(0.6)),
                            /* :: */[
                              Css.textAlign(Css.center),
                              /* :: */[
                                Css.padding(Css.zero),
                                /* [] */0
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var minimize = Css.style(/* :: */[
      Css.left(Css.em(2)),
      /* :: */[
        Css.backgroundColor(Css.hex("ffc100")),
        /* :: */[
          Css.borderColor(Css.hex("9d802c")),
          /* :: */[
            Css.color(Css.transparent),
            /* :: */[
              Css.hover(/* :: */[
                    Css.color(Css.black),
                    /* [] */0
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var zoom = Css.style(/* :: */[
      Css.left(Css.em(2)),
      /* :: */[
        Css.backgroundColor(Css.hex("00d742")),
        /* :: */[
          Css.borderColor(Css.hex("049931")),
          /* :: */[
            Css.color(Css.transparent),
            /* :: */[
              Css.hover(/* :: */[
                    Css.color(Css.black),
                    /* [] */0
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var quit = Css.style(/* :: */[
      Css.left(Css.em(2)),
      /* :: */[
        Css.backgroundColor(Css.hex("red")),
        /* :: */[
          Css.borderColor(Css.hex("049931")),
          /* :: */[
            Css.color(Css.transparent),
            /* :: */[
              Css.hover(/* :: */[
                    Css.color(Css.black),
                    /* [] */0
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var header = Css.style(/* :: */[
      Css.width(/* `percent */[
            -119887163,
            100
          ]),
      /* :: */[
        Css.height(Css.em(1)),
        /* :: */[
          Css.textAlign(Css.center),
          /* :: */[
            Css.paddingTop(Css.em(0.5)),
            /* :: */[
              Css.paddingBottom(Css.em(0.5)),
              /* :: */[
                Css.color(Css.black),
                /* :: */[
                  Css.backgroundColor(Css.whitesmoke),
                  /* :: */[
                    Css.borderTopLeftRadius(Css.px(5)),
                    /* :: */[
                      Css.borderTopRightRadius(Css.px(5)),
                      /* :: */[
                        Css.position(Css.relative),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

function make(shell, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("header", {
                          className: header
                        }, React.createElement("div", {
                              className: buttonContainer
                            }, React.createElement("button", {
                                  className: CommonStyles$Portfolio.combineClasses(/* :: */[
                                        quit,
                                        /* :: */[
                                          buttons,
                                          /* [] */0
                                        ]
                                      ])
                                }, Utils$Portfolio.str("x")), React.createElement("button", {
                                  className: CommonStyles$Portfolio.combineClasses(/* :: */[
                                        minimize,
                                        /* :: */[
                                          buttons,
                                          /* [] */0
                                        ]
                                      ])
                                }, Utils$Portfolio.str("-")), React.createElement("button", {
                                  className: CommonStyles$Portfolio.combineClasses(/* :: */[
                                        zoom,
                                        /* :: */[
                                          buttons,
                                          /* [] */0
                                        ]
                                      ])
                                }, Utils$Portfolio.str("+"))), Utils$Portfolio.str($$String.capitalize(shell)));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.buttonContainer = buttonContainer;
exports.buttons = buttons;
exports.minimize = minimize;
exports.zoom = zoom;
exports.quit = quit;
exports.header = header;
exports.make = make;
/* component Not a pure module */
