// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';


function text(prim) {
  return prim;
}

var defaultFont = " -apple-system, BlinkMacSystemFont,\n\\\"Segoe UI\\\",Roboto, Helvetica, Arial, sans-serif,\n  \\\"Apple Color Emoji\\\",\\\"Segoe UI Emoji\\\", \\\"Segoe UI Symbol\\\"\n  ";

exports.text = text;
exports.defaultFont = defaultFont;
/* No side effect */
